### ISSUE TITLE
Unable to execute the file "examples/dmcr/sac_aug.py"

### ISSUE THREAD

**Issue by darshitajain** [jakegrigsby/deep_control#30]
Thank you for your contribution. I am trying to execute the Pixel SAC with Data Augmentation code- examples/dmcr/sac_aug.py, but I am getting an error at line 10
from dmc_remastered.benchmarks import *. There is no such module as dmc_remastered.
How to resolve this?

@jakegrigsby Request your help in this matter.

**Comment by jakegrigsby** [comment]
Hi, dmc_remastered is a separate package (https://github.com/jakegrigsby/dmc_remastered). The Pixel SAC with data augmentation implementation was written for a paper about the DMC Remastered benchmark and was meant to be a compilation of some of the recent techniques at that time (late 2020) ([arXiv link](https://arxiv.org/abs/2010.06740)). If you are interested in image-based SAC but not that specific experiment, you might want to check out my other repo (https://github.com/jakegrigsby/super_sac) which puts more emphasis on those ideas. Another option is DrQV2 (https://github.com/facebookresearch/drqv2).

**Comment by darshitajain** [comment]
> 

Thank you. I shall check the other repository.
